events { worker_connections 1024; }

http {
    upstream nginx_backends {
        server nginx1:80;
        server nginx2:80;
        server nginx3:80;
    }

    server {
        listen 80;

        location / {
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            
            # Передаем реальный IP пользователя в X-Real-IP
            proxy_set_header X-Real-IP $remote_addr;
            
            proxy_pass http://nginx_backends;
        }
    }
}